# Generated by Django 3.0.8 on 2020-07-13 17:43

from django.db import migrations, models
import django.db.models.deletion
import qstm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('cellphone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qstm.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_parent', models.BooleanField(default=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('due_date', models.DateField(default=qstm.models.get_due_date)),
                ('class_topic', models.CharField(blank=True, max_length=250, null=True, verbose_name='Class')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('priority', models.CharField(choices=[('U', 'Urgent'), ('I', 'Important'), ('N', 'Normal'), ('L', 'Low')], default='Normal', max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qstm.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qstm.User'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=2083)),
                ('site_username', models.CharField(max_length=100)),
                ('site_password', models.CharField(max_length=100)),
                ('class_topic', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qstm.Student')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qstm.User'),
        ),
    ]
