# Generated by Django 3.0.8 on 2020-07-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0002_auto_20200713_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=9),
        ),
    ]
