# Generated by Django 3.0.8 on 2020-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0004_auto_20200713_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('U', 'Urgent'), ('I', 'Important'), ('N', 'Normal'), ('L', 'Low')], default='N', max_length=1),
        ),
    ]
