# Generated by Django 3.0.8 on 2020-07-13 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0005_auto_20200713_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 18, 28, 39, 955452)),
        ),
    ]
