# Generated by Django 3.0.8 on 2020-07-13 18:33

from django.db import migrations, models
import qstm.models


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0006_auto_20200713_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=qstm.models.get_due_date),
        ),
    ]
