# Generated by Django 3.0.8 on 2020-07-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0008_auto_20200713_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
