# Generated by Django 3.0.8 on 2020-07-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0009_auto_20200713_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
