# Generated by Django 3.0.8 on 2020-07-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qstm', '0010_auto_20200713_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_password',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_username',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_username',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
